export const ART_PATHS = {
  atlasUiChrome: '/art/atlas/atlas_ui_chrome.png',
  atlasPanelsTickets: '/art/atlas/atlas_panels_tickets.png',
  atlasIconsAvatarsItems: '/art/atlas/atlas_icons_avatars_items.png',
  atlasTexturesDecorations: '/art/atlas/atlas_textures_decorations.png',
} as const;

export const ART_ASSET_NAMES = [
  'logo_stamp',
  'top_hanging_sign',
  'top_hook_chain',
  'top_header_plaque',
  'status_chip_day',
  'status_chip_cash',
  'status_chip_profit',
  'status_chip_reputation',
  'status_chip_ap',
  'status_chip_inventory',
  'status_chip_hand',
  'phase_tab_idle',
  'phase_tab_active',
  'phase_tab_locked',
  'button_primary_large',
  'button_primary_medium',
  'button_confirm_green',
  'button_secondary_dark',
  'button_disabled',
  'panel_news_large',
  'panel_sidebar_small',
  'panel_log_mini',
  'panel_shop_status',
  'panel_inventory',
  'card_product_tag',
  'card_customer_large',
  'card_customer_small',
  'card_hand',
  'ticket_deal',
  'ledger_day_resolve',
  'board_run_report',
  'card_reward_choice',
  'modal_generic',
  'modal_danger',
  'paper_accident_report',
  'clipboard_evaluation',
  'placeholder_locked',
  'icon_day',
  'icon_cash',
  'icon_profit',
  'icon_reputation',
  'icon_ap',
  'icon_inventory',
  'icon_hand',
  'icon_opening',
  'icon_purchase',
  'icon_customer',
  'icon_draw',
  'icon_process',
  'icon_sell',
  'icon_resolve',
  'icon_reward',
  'icon_refresh',
  'icon_inspect',
  'icon_package',
  'icon_pr',
  'icon_wash',
  'icon_warning',
  'avatar_hr_female',
  'avatar_startup_boss',
  'avatar_headhunter',
  'avatar_state_interviewer',
  'avatar_partner',
  'meat_cut_01',
  'meat_cut_02',
  'meat_cut_03',
  'card_art_precise_cut',
  'card_art_package',
  'card_art_report',
  'card_art_pr_crisis',
  'reward_briefcase',
  'reward_heart_box',
  'reward_ring_light',
  'reward_mystery_crate',
  'texture_dark_leather',
  'texture_old_paper',
  'texture_red_lacquer',
] as const;

